### PR TITLE
Connect g0v #edu-open-stu-association on Slack with NTNUCSIE Student Association Discord

### PR DESCRIPTION
**Pull request by skyhong2002**
Connect g0v #edu-open-stu-association on Slack with NTNUCSIE Student Association Discord.
Discord Invite Link: https://discord.gg/778zGXGjKf

### CODE REVIEW

**Comment by pm5** [comment]
Got an error when the service starts:

```
[0001] ERROR discord:      could not find Discord server "1100463831085498509"
[0001]  INFO discord:      Possible server values:
[0001]  INFO discord:           - Server="NTNUCSIE Student Association" # by name
[0001]  INFO discord:           - Server="1100299021744078900" # by ID
[0001] FATAL main:         Starting gateway failed: Bridge discord.opensantnucsie failed to start: could not find Discord server "1100463831085498509"
```

**Comment by pm5** [comment]
Got another error if replacing server ID with the suggested one:

```
[0003]  INFO router:       Starting bridge: discord.opensantnucsie
[0003]  INFO discord:      Connecting
[0003]  INFO discord:      Connection succeeded
[0005] ERROR discord:      Error obtaining server members: HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}
[0005] FATAL main:         Starting gateway failed: Bridge discord.opensantnucsie failed to start: HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}
```

Probably missing permissions on Discord?

**Comment by skyhong2002** [comment]
> Probably missing permissions on Discord?

Yes, the permissions are indeed not permitted. I fixed it and granted permission on the server side, too.
Sorry for the inconvenience  qwqqq

Screenshot 2023-05-02 at 19 17 51

**Comment by pm5** [comment]
No problem at all.  Welcome!  The configuration seems to work.  But when I logged in to NTNUCSIE Student Association Discord server, I couldn't find the edu-open-stu-association channel.  Is it a private channel?

**Comment by skyhong2002** [comment]
Yes, I set the channel to private yet it was not supposed to be. 
Everything works fine. Thank you a lot for the effort!

**Pull request merged**
